import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {hasApplicationForm,choosePosting,postingLinks} from '../src/form-navigation.ts';
const b=await chromium.launch();const p=await b.newPage();
await p.setContent('<h1>Stellenangebote</h1><form><h2>Kontakt</h2><input name="vorname"><input name="nachname"><input type="email"><textarea></textarea><button>Jetzt absenden</button></form>');
assert.equal(await hasApplicationForm(p),false,'contact/sidebar form must not stop navigation');
await p.setContent('<h1>Contact</h1><form><input name="name"><input type="email"><input type="file"><button>Send</button></form>');
assert.equal(await hasApplicationForm(p),false,'arbitrary attachment is not proof of an application');
await p.setContent('<h1>Application form</h1><input name="name"><input type="email"><label>Application documents<input type="file"></label>');
assert.equal(await hasApplicationForm(p),true,'actual shared-upload application should be accepted');
const job:any={title:'Wissenschaftliche Mitarbeiter (m/w/d)',location:'Nicht angegeben'};
const store:any={kvGet:async()=>null,kvSet:async()=>{}};
const links=[{title:job.title,location:'Berlin',url:'https://example.com/job/berlin'},{title:job.title,location:'Köln',url:'https://example.com/job/koeln'}];
assert.equal((await choosePosting([...links,{...links[1],title:'MEHR ERFAHREN',location:''}],job,store))?.location,'Köln');
assert.equal((await choosePosting(links,{...job,location:'Berlin'},store))?.location,'Berlin');
assert.equal(await choosePosting(links.map(l=>({...l,location:''})),job,store),null,'do not guess ambiguous locations');
assert.equal(await choosePosting([{title:'Rechtsanwalt',location:'Köln',url:'https://example.com/job/a'}],job,store),null);
await p.setContent('<article><h2>Wissenschaftliche Mitarbeiter (m/w/d)</h2><span class="job-location">Köln</span><div hidden><a href="https://example.com/job/koeln">Mehr erfahren</a></div></article>');
assert.equal((await postingLinks(p))[0].url,'https://example.com/job/koeln','collapsed detail link remains resolvable');
await b.close();
const {extractJobCards}=await import('../src/sources/html.ts');
const cards=extractJobCards('<div class="job-item"><div class="job-item-titel">Wissenschaftliche Mitarbeiter</div><div class="job-item-standort">Köln</div><a href="/job/koeln/">Mehr erfahren</a></div><div class="job-item"><div class="job-item-titel">Wissenschaftliche Mitarbeiter</div><div class="job-item-standort">Berlin</div><a href="/job/berlin/">Mehr erfahren</a></div>','https://example.com/stellenangebote/');
assert.equal(cards.length,2);assert.equal(cards[0].location,'Köln');assert.equal(cards[0].url,'https://example.com/job/koeln/');
console.log('PASS: contact rejection, shared document form, job/location identity and collapsed detail navigation');
